title: OSEP Notes
description: Notes for OSEP
theme: just-the-docs

url: https://github.com/satanicang3l/osepnotes

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/satanicang3l/osepnotes
